import { Event } from './event.model';

export type CreateExpedition = {
  name: ExpeditionName;
  beginDateTime: string;
  hasTuningOrb: boolean;
  role: Role;
};

export type DeleteExpedition = {
  id: number;
};

export type JoinExpedition = {
  id: number;
  role: Role;
  hasTuningOrb: boolean;
};

export type LeaveExpedition = {
  id: number;
};

export type Expedition = {
  id: number;
  name: string;
  beginDateTime: string;
  participants: Participant[];
  owner: Owner;
};

export type Participant = {
  userId: number;
  characterName: string;
  discordId: string;
  role: Role;
  hasTuningOrb: boolean;
};

export type Owner = {
  userId: number;
  characterName: string;
  discordId: string;
};

export enum Role {
  TANK = 'TANK',
  DAMAGE = 'DAMAGE',
  HEAL = 'HEAL',
}

export enum ExpeditionName {
  AMRINE_EXCAVATION = 'AMRINE_EXCAVATION',
  STARSTONE_BARROWS = 'STARSTONE_BARROWS',
  THE_DEPTHS = 'THE_DEPTHS',
  DYNASTY_SHIPYARD = 'DYNASTY_SHIPYARD',
  LAZARUS_INSTRUMENTALITY = 'LAZARUS_INSTRUMENTALITY',
  GARDEN_OF_GENESIS = 'GARDEN_OF_GENESIS',
  TEMPEST_REGULAR = 'TEMPEST_REGULAR',
  ENNEAD_REGULAR = 'ENNEAD_REGULAR',
  BLACK_REGULAR = 'BLACK_REGULAR',
  STARSTONE_BARROWS_MUTATED = 'STARSTONE_BARROWS_MUTATED',
  STARSTONE_BARROWS_M2 = 'STARSTONE_BARROWS_M2',
  STARSTONE_BARROWS_M3 = 'STARSTONE_BARROWS_M3',
  STARSTONE_BARROWS_M4 = 'STARSTONE_BARROWS_M4',
  STARSTONE_BARROWS_M5 = 'STARSTONE_BARROWS_M5',
  STARSTONE_BARROWS_M6 = 'STARSTONE_BARROWS_M6',
  STARSTONE_BARROWS_M7 = 'STARSTONE_BARROWS_M7',
  STARSTONE_BARROWS_M8 = 'STARSTONE_BARROWS_M8',
  STARSTONE_BARROWS_M9 = 'STARSTONE_BARROWS_M9',
  STARSTONE_BARROWS_M10 = 'STARSTONE_BARROWS_M10',
  THE_DEPTHS_MUTATED = 'THE_DEPTHS_MUTATED',
  THE_DEPTHS_M2 = 'THE_DEPTHS_M2',
  THE_DEPTHS_M3 = 'THE_DEPTHS_M3',
  THE_DEPTHS_M4 = 'THE_DEPTHS_M4',
  THE_DEPTHS_M5 = 'THE_DEPTHS_M5',
  THE_DEPTHS_M6 = 'THE_DEPTHS_M6',
  THE_DEPTHS_M7 = 'THE_DEPTHS_M7',
  THE_DEPTHS_M8 = 'THE_DEPTHS_M8',
  THE_DEPTHS_M9 = 'THE_DEPTHS_M9',
  THE_DEPTHS_M10 = 'THE_DEPTHS_M10',
  DYNASTY_SHIPYARD_MUTATED = 'DYNASTY_SHIPYARD_MUTATED',
  DYNASTY_SHIPYARD_M2 = 'DYNASTY_SHIPYARD_M2',
  DYNASTY_SHIPYARD_M3 = 'DYNASTY_SHIPYARD_M3',
  DYNASTY_SHIPYARD_M4 = 'DYNASTY_SHIPYARD_M4',
  DYNASTY_SHIPYARD_M5 = 'DYNASTY_SHIPYARD_M5',
  DYNASTY_SHIPYARD_M6 = 'DYNASTY_SHIPYARD_M6',
  DYNASTY_SHIPYARD_M7 = 'DYNASTY_SHIPYARD_M7',
  DYNASTY_SHIPYARD_M8 = 'DYNASTY_SHIPYARD_M8',
  DYNASTY_SHIPYARD_M9 = 'DYNASTY_SHIPYARD_M9',
  DYNASTY_SHIPYARD_M10 = 'DYNASTY_SHIPYARD_M10',
  LAZARUS_INSTRUMENTALITY_MUTATED = 'LAZARUS_INSTRUMENTALITY_MUTATED',
  LAZARUS_INSTRUMENTALITY_M2 = 'LAZARUS_INSTRUMENTALITY_M2',
  LAZARUS_INSTRUMENTALITY_M3 = 'LAZARUS_INSTRUMENTALITY_M3',
  LAZARUS_INSTRUMENTALITY_M4 = 'LAZARUS_INSTRUMENTALITY_M4',
  LAZARUS_INSTRUMENTALITY_M5 = 'LAZARUS_INSTRUMENTALITY_M5',
  LAZARUS_INSTRUMENTALITY_M6 = 'LAZARUS_INSTRUMENTALITY_M6',
  LAZARUS_INSTRUMENTALITY_M7 = 'LAZARUS_INSTRUMENTALITY_M7',
  LAZARUS_INSTRUMENTALITY_M8 = 'LAZARUS_INSTRUMENTALITY_M8',
  LAZARUS_INSTRUMENTALITY_M9 = 'LAZARUS_INSTRUMENTALITY_M9',
  LAZARUS_INSTRUMENTALITY_M10 = 'LAZARUS_INSTRUMENTALITY_M10',
  GARDEN_OF_GENESIS_MUTATED = 'GARDEN_OF_GENESIS_MUTATED',
  GARDEN_OF_GENESIS_M2 = 'GARDEN_OF_GENESIS_M2',
  GARDEN_OF_GENESIS_M3 = 'GARDEN_OF_GENESIS_M3',
  GARDEN_OF_GENESIS_M4 = 'GARDEN_OF_GENESIS_M4',
  GARDEN_OF_GENESIS_M5 = 'GARDEN_OF_GENESIS_M5',
  GARDEN_OF_GENESIS_M6 = 'GARDEN_OF_GENESIS_M6',
  GARDEN_OF_GENESIS_M7 = 'GARDEN_OF_GENESIS_M7',
  GARDEN_OF_GENESIS_M8 = 'GARDEN_OF_GENESIS_M8',
  GARDEN_OF_GENESIS_M9 = 'GARDEN_OF_GENESIS_M9',
  GARDEN_OF_GENESIS_M10 = 'GARDEN_OF_GENESIS_M10',
  TEMPEST_MUTATED = 'TEMPEST_MUTATED',
  TEMPEST_M2 = 'TEMPEST_M2',
  TEMPEST_M3 = 'TEMPEST_M3',
  TEMPEST_M4 = 'TEMPEST_M4',
  TEMPEST_M5 = 'TEMPEST_M5',
  TEMPEST_M6 = 'TEMPEST_M6',
  TEMPEST_M7 = 'TEMPEST_M7',
  TEMPEST_M8 = 'TEMPEST_M8',
  TEMPEST_M9 = 'TEMPEST_M9',
  TEMPEST_M10 = 'TEMPEST_M10',
  ENNEAD_MUTATED = 'ENNEAD_MUTATED',
  ENNEAD_M2 = 'ENNEAD_M2',
  ENNEAD_M3 = 'ENNEAD_M3',
  ENNEAD_M4 = 'ENNEAD_M4',
  ENNEAD_M5 = 'ENNEAD_M5',
  ENNEAD_M6 = 'ENNEAD_M6',
  ENNEAD_M7 = 'ENNEAD_M7',
  ENNEAD_M8 = 'ENNEAD_M8',
  ENNEAD_M9 = 'ENNEAD_M9',
  ENNEAD_M10 = 'ENNEAD_M10',
  BLACK_MUTATED = 'BLACK_MUTATED',
  BLACK_M2 = 'BLACK_M2',
  BLACK_M3 = 'BLACK_M3',
  BLACK_M4 = 'BLACK_M4',
  BLACK_M5 = 'BLACK_M5',
  BLACK_M6 = 'BLACK_M6',
  BLACK_M7 = 'BLACK_M7',
  BLACK_M8 = 'BLACK_M8',
  BLACK_M9 = 'BLACK_M9',
  BLACK_M10 = 'BLACK_M10',
}

export class ExpeditionCreateEvent implements Event {
  id = 'EXPEDITION.CREATE';
  constructor(public expedition: Expedition) {}
}

export class ExpeditionDeleteEvent implements Event {
  id = 'EXPEDITION.DELETE';
  constructor(public expeditionId: number) {}
}

export class ExpeditionJoinEvent implements Event {
  id = 'EXPEDITION.JOIN';
  constructor(public expedition: Expedition) {}
}

export class ExpeditionLeaveEvent implements Event {
  id = 'EXPEDITION.LEAVE';
  constructor(public expedition: Expedition) {}
}
